services:
  user_service:
    container_name: ${USER_SERVICE_CONTAINER}
    build:
      context: .
      dockerfile: user_service/Dockerfile
    ports:
      - "${USER_SERVICE_PORT}:${USER_SERVICE_PORT}"
    networks:
      - microservices_network
    depends_on:
      - database
    environment:
      DATABASE_HOST: ${DATABASE_HOST}  
      DATABASE_USER: ${DATABASE_USER}  
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}  
      DATABASE_NAME: ${DATABASE_NAME}  
      DATABASE_PORT: ${DATABASE_PORT}  

  database:
    container_name: ${DATABASE_CONTAINER}
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}  
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  
      POSTGRES_DB: ${DATABASE_NAME}  
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices_network

networks:
  microservices_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local